import React from "react";

export const Skills = () => {
    return (
        <div>
            <div className="skills padd-15">
                      <h2>Skills</h2>
                      <img
                        src="https://img.shields.io/badge/chakra ui-%234ED1C5.svg?style=for-the-badge&logo=chakraui&logoColor=white"
                        align="center"
                        alt="chakra-ui"
                      />
                      <img
                        src="https://img.shields.io/badge/rest api-%23000000.svg?style=for-the-badge&logo=flask&logoColor=white"
                        align="center"
                        alt="restapi"
                      />
                      <img
                        src="https://img.shields.io/badge/javascript-%23323330.svg?style=for-the-badge&logo=javascript&logoColor=%23F7DF1E"
                        align="center"
                        alt="javascript"
                      />
                      <img
                        src="https://img.shields.io/badge/express.js-%23404d59.svg?style=for-the-badge&logo=express&logoColor=%2361DAFB"
                        align="center"
                        alt="express"
                      />
                      <img
                        src="https://img.shields.io/badge/node.js-6DA55F?style=for-the-badge&logo=node.js&logoColor=white"
                        align="center"
                        alt="node.js"
                      />
                      <img
                        src="https://img.shields.io/badge/typescript-%23007ACC.svg?style=for-the-badge&logo=typescript&logoColor=white"
                        align="center"
                        alt="type script"
                      />
                      <img
                        src="https://img.shields.io/badge/html5-%23E34F26.svg?style=for-the-badge&logo=html5&logoColor=white"
                        align="center"
                        alt="html5"
                      />
                      <img
                        src="https://img.shields.io/badge/css3-%231572B6.svg?style=for-the-badge&logo=css3&logoColor=white"
                        align="center"
                        alt="css3"
                      />
                      <img
                        src="https://img.shields.io/badge/MongoDB-%234ea94b.svg?style=for-the-badge&logo=mongodb&logoColor=white"
                        align="center"
                        alt="mongodb"
                      />
                      <img
                        src="https://img.shields.io/badge/React-20232A?style=for-the-badge&logo=react&logoColor=61DAFB"
                        align="center"
                        alt="reactjs"
                      />
                      <img
                        src="https://img.shields.io/badge/Redux-593D88?style=for-the-badge&logo=redux&logoColor=white"
                        align="center"
                        alt="redux"
                      />
                      <img
                        src="https://img.shields.io/badge/Material%20UI-007FFF?style=for-the-badge&logo=mui&logoColor=white"
                        align="center"
                        alt="material-ui"
                      />
                      <img
                        src="https://img.shields.io/badge/React_Router-CA4245?style=for-the-badge&logo=react-router&logoColor=white"
                        align="center"
                        alt="react-router"
                      />
                      <h2>Tools</h2>
                      <img
                        src="https://img.shields.io/badge/heroku-%23430098.svg?style=for-the-badge&logo=heroku&logoColor=white"
                        align="center"
                        alt="git"
                      />
                      <img
                        src="https://img.shields.io/badge/netlify-%23000000.svg?style=for-the-badge&logo=netlify&logoColor=#00C7B7"
                        align="center"
                        alt="git"
                      />
                      <img
                        src="https://img.shields.io/badge/vercel-%23000000.svg?style=for-the-badge&logo=vercel&logoColor=whit"
                        align="center"
                        alt="git"
                      />
                      <img
                        src="https://img.shields.io/badge/NPM-%23000000.svg?style=for-the-badge&logo=npm&logoColor=white"
                        align="center"
                        alt="npm"
                      />
                      <img
                        src="https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white"
                        align="center"
                        alt="github"
                      />
                      <img
                        src="https://img.shields.io/badge/Postman-FF6C37?style=for-the-badge&logo=postman&logoColor=white"
                        align="center"
                        alt="postman"
                      />
                      </div>
        </div>
    );
}