// Description
// Alan Turing, the mathematician, is trying to break the encrypted messages of the German Troops, generated by their encryption device "Enigma". To find the distribution of characters, he needs to find out how many times a particular character appears in a string. But, to feed the data into his computer, "Christopher", he needs the data in lexicographic order, that is, in alphabetical order. Since, he is busy making "Christopher" better, he asks you for help. Help Alan find the frequency of characters in the encrypted strings in alphabetical order. The string contains only lower case alphabets.

// Input
// The first line contains N, the length of the string, and the next line contains the string itself.

let n = 4;
let str = "aman";

function alanFrequency(n,str)
{
    str=str.split("");
    str=str.sort().join("");
    
    let obj = {};
    
    for(let i=0; i<n; i++)
    {
        if(obj[str[i]] === undefined)
        {
            obj[str[i]]=1;
        }
        else{
            obj[str[i]]=obj[str[i]]+1;
        }
    }
    for(let key in obj){
        console.log(key+"-"+obj[key]);
    }
}


function runProgram(input){
   
    input = input.trim().split("\n");
    var n = +input[0].trim();
    var str = input[1].trim();
    
    alanFrequency(n,str);
}

if(process.env.USER===""){
    runProgram('');
}else{
    process.stdin.resume();
    process.stdin.setEncoding("ascii");
    let read="";
    process.stdin.on("data",function(input){
        read+=input;
    });
    process.stdin.on("end",function(){
        read=read.replace(/\n$/,"");
        read=read.replace(/\n$/,'');
        runProgram(read);
    });
    process.on('SIGINT',function(){
        read=read.replace(/\n$/,"");
        runProgram(read);
        process.exit(0);
    });
}
